spring:
    application:
        name: parceiro_api
    datasource:
        name: parceirodb
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/parceirodb
        username: postgres
        password: 1234
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: none
    jackson:
        property-naming-strategy: SNAKE_CASE
        deserialization:
            fail-on-null-for-primitives: false
    flyway:
        baseline-on-migrate: true
        baseline-version: 0
        clean-disabled: false
logging:
    charset:
        console: UTF-8
    level:
        root: info
server:
    port: 8080
springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
api:
    security:
        token:
            secret: secret