spring:
    application:
        name: parceiro_api
    datasource:
        name: parceirodb
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/parceirodb
        username: postgres
        password: 1234
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: none
    jackson:
        property-naming-strategy: SNAKE_CASE
        deserialization:
            fail-on-null-for-primitives: false
    flyway:
        baseline-on-migrate: true
        baseline-version: 0
        clean-disabled: false
logging:
    charset:
        console: UTF-8
    level:
        root: info
server:
    port: 8080
springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
api:
    security:
        token:
            secret: secret
resilience4j:
    circuitbreaker:
        instances:
            backendGlobalBreaker:
                slidingWindowSize: 10
                failureRateThreshold: 50
                waitDurationInOpenState: 10s
                ignoreExceptions:
                - com.parceiroferramentas.api.parceiro_api.exception.BadRequestException
                - com.parceiroferramentas.api.parceiro_api.exception.InternalApplicationException
                - com.parceiroferramentas.api.parceiro_api.exception.InvalidAuthorizationException
                - com.parceiroferramentas.api.parceiro_api.exception.NotFoundException
    retry:
        instances:
            backendGlobalRetry:
                maxAttempts: 3
                waitDuration: 1000ms
                retryExceptions:
                - org.springframework.dao.DataAccessException
                - java.net.SocketTimeoutException
                - java.io.IOException
                ignoreExceptions:
                - com.parceiroferramentas.api.parceiro_api.exception.BadRequestException
                - com.parceiroferramentas.api.parceiro_api.exception.InternalApplicationException
                - com.parceiroferramentas.api.parceiro_api.exception.InvalidAuthorizationException
                - com.parceiroferramentas.api.parceiro_api.exception.NotFoundException

    ratelimiter:
        instances:
            authRateLimit:
                limitForPeriod: 5
                limitRefreshPeriod: 5s
                timeoutDuration: 0
            pedidosRateLimit:
                limitForPeriod: 2
                limitRefreshPeriod: 1m
                timeoutDuration: 10s