spring:
    application:
        name: parceiro_api
    datasource:
        name: parceirodb
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: none
    jackson:
        property-naming-strategy: SNAKE_CASE
        deserialization:
            fail-on-null-for-primitives: false
    flyway:
        baseline-on-migrate: true
        baseline-version: 0
        clean-disabled: false
logging:
    charset:
        console: UTF-8
    level:
        root: info
        "[com.parceiroferramentas.api]": DEBUG
    pattern:
        console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow} %clr($$   {LOG_LEVEL_PATTERN:-%5p}) %clr(   $${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
        file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    structured:
        format:
            console: ecs
            file: ecs
    file:
        name: parceiro-api.log
server:
    port: 8080
springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
api:
    security:
        token:
            secret: ${JWT_SECRET}
resilience4j:
    circuitbreaker:
        instances:
            backendGlobalBreaker:
                slidingWindowSize: 10
                failureRateThreshold: 50
                waitDurationInOpenState: 8s
                ignoreExceptions:
                - com.parceiroferramentas.api.parceiro_api.exception.BadRequestException
                - com.parceiroferramentas.api.parceiro_api.exception.InternalApplicationException
                - com.parceiroferramentas.api.parceiro_api.exception.InvalidAuthorizationException
                - com.parceiroferramentas.api.parceiro_api.exception.NotFoundException
    retry:
        instances:
            backendGlobalRetry:
                maxAttempts: 3
                waitDuration: 500ms
                retryExceptions:
                - org.springframework.dao.DataAccessException
                - java.net.SocketTimeoutException
                - java.io.IOException
                ignoreExceptions:
                - com.parceiroferramentas.api.parceiro_api.exception.BadRequestException
                - com.parceiroferramentas.api.parceiro_api.exception.InternalApplicationException
                - com.parceiroferramentas.api.parceiro_api.exception.InvalidAuthorizationException
                - com.parceiroferramentas.api.parceiro_api.exception.NotFoundException

    ratelimiter:
        instances:
            authRateLimit:
                limitForPeriod: 5
                limitRefreshPeriod: 5s
                timeoutDuration: 0
            pedidosRateLimit:
                limitForPeriod: 2
                limitRefreshPeriod: 1m
                timeoutDuration: 10s
management:
    endpoints:
        web:
            exposure:
                include:
                - health
                - info
                - prometheus
                - metrics
    endpoint:
        health:
            show-details: always
    prometheus:
        metrics:
            export:
                enabled: true